# Generated by Django 4.1.1 on 2022-09-13 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
        ('applications', '0002_application_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='Job'),
            preserve_default=False,
        ),
    ]
